### ISSUE TITLE
Access to ICCOM in Linux Kernel

### ISSUE THREAD

**Issue by uic03393** [CogentEmbedded/kernel-module-iccom#1]
Hi, i need to access ICCOM on Linux Kernel. How can i actually call function, such as "Iccom_lib_Init" as declared in "Iccom_kernel_api.c"?

**Comment by nikita-yoush** [comment]
I don't understand the question. Function is exported and you can call it in your kernel module code in the same was as you call any other function there.

**Comment by uic03393** [comment]
Hi, I am calling "Iccom_lib_Init" from "kernel-source\net\bluetooth\af_bluetooth.c as below.

---------------------------------
extern int32_t Iccom_lib_Init(const Iccom_init_param *pIccomInit, Iccom_channel_t *pChannelHandle);

func() { err = Iccom_lib_Init(&ip, &pch); }

---------------------------------

When I run "bitbake virtual/kernel", it returns error:
**"ERROR: "Iccom_lib_Init" [net/bluetooth/bluetooth.ko] undefined!"**

**Comment by nikita-yoush** [comment]
You can't call symbol defined in external module from code built into the kernel image.
Possible option for you is stop modifying kernel bluetooth core and write your code in your own module.

**Comment by uic03393** [comment]
I am trying to create new domain which call ICCOM under socket protocol. So user can activate ICCOM by calling socket() from user space. Sound like it's not feasible? Please correct me, thx

**Comment by nikita-yoush** [comment]
If you need iccom from userspace then you can just use userspace iccom library.

If you want to create a new socket-based userspace API for iccom - ok you can do that, create a new socket family etc etc. You definitely don't need to touch bluetooth code for that. Write your code inside a new kernel module, define your socket family, register it inside network layer, and implement all required methods. You will have to write a lot of code, check existing socket families for examples.
